pragma Singleton

import qs.services
import qs.modules.common
import qs.modules.common.functions
import Quickshell
import Quickshell.Io
import QtQuick

/**
 * Turns Config.options.idle into ~/.config/hypr/hypridle.conf, split by power
 * source the way Windows' "Screen, sleep" panel is: separate lock/screen-off/
 * suspend timers for on-battery and plugged-in, switched the moment the
 * machine crosses that line.
 *
 * hypridle has no live-reload, so a change here means writing the file and
 * restarting the daemon. `generatedConf` is a single computed property that
 * reads everything it depends on — the active profile's five knobs and
 * Battery.isPluggedIn/available — so any of those changing re-derives it
 * through ordinary QML binding.
 */
Singleton {
    id: root

    readonly property string hypridleConfPath: FileUtils.trimFileProtocol(`${Directories.config}/hypr/hypridle.conf`)

    // No battery at all (desktop) counts as permanently on AC — matches Windows
    // hiding the "on battery" column entirely when there's nothing to run one on.
    readonly property bool onAC: !Battery.available || Battery.isPluggedIn
    readonly property var activeProfile: onAC ? Config.options.idle.ac : Config.options.idle.battery

    function listener(timeoutSeconds, onTimeout, onResume) {
        return `\nlistener {\n    timeout = ${timeoutSeconds}\n    on-timeout = ${onTimeout}\n`
            + (onResume ? `    on-resume = ${onResume}\n` : "") + `}\n`;
    }

    readonly property string generatedConf: {
        const p = root.activeProfile;
        let listeners = "";
        if (p.lockEnable)
            listeners += root.listener(Math.max(1, p.lockMinutes) * 60, "loginctl lock-session");
        if (p.screenOffEnable)
            listeners += root.listener(Math.max(1, p.screenOffMinutes) * 60,
                `hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'`,
                `hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'`);
        if (p.suspendEnable)
            listeners += root.listener(Math.max(1, p.suspendMinutes) * 60, "$suspend_cmd");

        return "# Generated by IdleManager.qml from Settings > Idle & power. Manual edits are\n"
            + "# overwritten the next time an idle setting changes or the power source flips.\n"
            + `$lock_cmd = hyprctl dispatch 'hl.dsp.global("quickshell:lock")' & pidof qs quickshell hyprlock || hyprlock\n`
            + `$suspend_cmd = systemctl suspend || loginctl suspend\n\n`
            + "general {\n"
            + "    lock_cmd = $lock_cmd\n"
            + "    before_sleep_cmd = loginctl lock-session\n"
            + `    after_sleep_cmd = hyprctl dispatch 'hl.dsp.global("quickshell:lockFocus")'\n`
            + "    inhibit_sleep = 3\n"
            + "}\n"
            + listeners;
    }

    // UPower's displayDevice is still null for a beat after startup, so the very
    // first evaluation of `onAC` above routinely happens before Battery.available
    // is populated — every laptop looks like a desktop for that first tick, and
    // whatever generatedConf comes out of it is wrong. Tracked in memory rather
    // than diffed against FileView.text(), which does not reliably reflect a
    // setText() this object just made itself; a plain string comparison here
    // can't be wrong about what it last wrote.
    property string lastAppliedConf: ""

    onGeneratedConfChanged: root.apply()
    Component.onCompleted: root.apply()

    // Belt-and-suspenders alongside the generatedConf binding above: Battery's
    // own properties are the one dependency here that changes for a reason
    // external to this file (a cable, not a setting), so it gets an explicit
    // listener rather than trusting the binding graph alone to notice.
    Connections {
        target: Battery
        function onAvailableChanged() {
            root.apply();
        }
        function onIsPluggedInChanged() {
            root.apply();
        }
    }

    function apply() {
        if (!hypridleFile.loaded)
            return; // Wait for the initial read so the first diff is meaningful.
        if (root.generatedConf === root.lastAppliedConf)
            return;
        root.lastAppliedConf = root.generatedConf;
        hypridleFile.setText(root.generatedConf);
        // hypridle reads its config once at startup; restarting is the only way
        // to pick up a change. `exec` in place of the shell so nothing is left
        // wrapping the daemon.
        restartProc.running = false;
        restartProc.running = true;
    }

    FileView {
        id: hypridleFile
        property bool loaded: false
        path: Qt.resolvedUrl(root.hypridleConfPath)
        onLoaded: {
            // Whatever is already on disk counts as "applied" so a shell restart
            // that changes nothing doesn't kill and relaunch hypridle for no
            // reason — only an actual difference should do that.
            root.lastAppliedConf = hypridleFile.text();
            hypridleFile.loaded = true;
            root.apply();
        }
        onLoadFailed: error => {
            hypridleFile.loaded = true;
            root.apply();
        }
    }

    Process {
        id: restartProc
        command: ["bash", "-c", "pkill -x hypridle; sleep 0.15; exec hypridle"]
    }
}
